using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CopilotActivator
{
    public partial class CopilotActivator : Form
    {
        public CopilotActivator()
        {
            InitializeComponent();
        }

        public static string tmpPath = Path.GetTempPath();

        public static string githubPage = "https://github.com/SelyanSel/WindowsCopilotActivator";

        private static void ActivateCopilot()
        {
            RegistryKey key = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\Shell\Copilot\BingChat", true);

            if (File.Exists(tmpPath + @"\cactivator22H3.exe")){ File.Delete(tmpPath + @"\cactivator22H3.exe"); }

            if (key.GetValue("IsUserEligible").ToString() == "1")
            {
                if (MessageBox.Show(new Form() { TopMost = true }, "Copilot is already enabled on this computer." +
                                                                   "Do you want to create a new shortcut on your desktop?",
                                                                   "Copilot Activator", MessageBoxButtons.YesNo) == DialogResult.Yes)
                {
                    File.Copy(Application.StartupPath + @"\" + System.AppDomain.CurrentDomain.FriendlyName, tmpPath + @"\cactivator22H3.exe");
                    string desk = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);

                    using (StreamWriter writer = new StreamWriter(desk + "\\" + "Start Windows Copilot" + ".cmd"))
                    {
                        writer.WriteLine("# Generated by CopilotActivator ; " + githubPage + Environment.NewLine);
                        writer.WriteLine("start " + tmpPath + @"\cactivator22H3.exe" + " --quickstart && exit /B");
                    }

                    MessageBox.Show("Activation successful. " +
                            "Start copilot with the shortcut on your desktop!",
                            "Error", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    return;
                }
            }

            if (key != null)
            {
                key.SetValue("IsUserEligible", 1, RegistryValueKind.DWord);
            }
            else
            {
                MessageBox.Show("Your computer is incompatible. Make sure to have the latest windows version," +
                                " and check for the latest updates on the github.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            MessageBox.Show("Activation successful. " +
                            "Start copilot with the shortcut on your desktop!",
                            "Error", MessageBoxButtons.OK, MessageBoxIcon.Information);

            if (File.Exists(tmpPath + @"\cactivator22H3.exe")){File.Delete(tmpPath + @"\cactivator22H3.exe");}

            File.Copy(Application.StartupPath + @"\" + System.AppDomain.CurrentDomain.FriendlyName, tmpPath + @"\cactivator22H3.exe");
            string desktop = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);

            using (StreamWriter writer = new StreamWriter(desktop + "\\" + "Start Windows Copilot" + ".cmd"))
            {
                writer.WriteLine("# Generated by CopilotActivator ; " + githubPage + Environment.NewLine);
                writer.WriteLine("start " + tmpPath + @"\cactivator22H3.exe" + " --quickstart && exit /B");
            }

        }

        private void button1_Click(object sender, EventArgs e)
        {
            ActivateCopilot();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            System.Diagnostics.Process.Start(githubPage);
        }
    }
}
